trigger:
  batch: true
  branches:
    include:
    - master
    exclude:
    - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
    - master

stages:
- stage: test
  displayName: "Run tests"
  - template: tests-template.yml
